//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazzino.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Articolo", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    public partial class Articolo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDprodottoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrezzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantitaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDprodotto {
            get {
                return this.IDprodottoField;
            }
            set {
                if ((this.IDprodottoField.Equals(value) != true)) {
                    this.IDprodottoField = value;
                    this.RaisePropertyChanged("IDprodotto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Prezzo {
            get {
                return this.PrezzoField;
            }
            set {
                if ((this.PrezzoField.Equals(value) != true)) {
                    this.PrezzoField = value;
                    this.RaisePropertyChanged("Prezzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantita {
            get {
                return this.QuantitaField;
            }
            set {
                if ((this.QuantitaField.Equals(value) != true)) {
                    this.QuantitaField = value;
                    this.RaisePropertyChanged("Quantita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utente", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    public partial class Utente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Data_nascitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndirizzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PswField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome {
            get {
                return this.CognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CognomeField, value) != true)) {
                    this.CognomeField = value;
                    this.RaisePropertyChanged("Cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data_nascita {
            get {
                return this.Data_nascitaField;
            }
            set {
                if ((this.Data_nascitaField.Equals(value) != true)) {
                    this.Data_nascitaField = value;
                    this.RaisePropertyChanged("Data_nascita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Indirizzo {
            get {
                return this.IndirizzoField;
            }
            set {
                if ((object.ReferenceEquals(this.IndirizzoField, value) != true)) {
                    this.IndirizzoField = value;
                    this.RaisePropertyChanged("Indirizzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Psw {
            get {
                return this.PswField;
            }
            set {
                if ((object.ReferenceEquals(this.PswField, value) != true)) {
                    this.PswField = value;
                    this.RaisePropertyChanged("Psw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Login", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    public partial class Login : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckEmail", ReplyAction="http://tempuri.org/IService1/CheckEmailResponse")]
        bool CheckEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckEmail", ReplyAction="http://tempuri.org/IService1/CheckEmailResponse")]
        System.Threading.Tasks.Task<bool> CheckEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminaProdotto", ReplyAction="http://tempuri.org/IService1/EliminaProdottoResponse")]
        bool EliminaProdotto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminaProdotto", ReplyAction="http://tempuri.org/IService1/EliminaProdottoResponse")]
        System.Threading.Tasks.Task<bool> EliminaProdottoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategoria", ReplyAction="http://tempuri.org/IService1/GetCategoriaResponse")]
        string GetCategoria(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategoria", ReplyAction="http://tempuri.org/IService1/GetCategoriaResponse")]
        System.Threading.Tasks.Task<string> GetCategoriaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProdotto", ReplyAction="http://tempuri.org/IService1/GetProdottoResponse")]
        Magazzino.ServiceReference1.Articolo GetProdotto(int IDProdotto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProdotto", ReplyAction="http://tempuri.org/IService1/GetProdottoResponse")]
        System.Threading.Tasks.Task<Magazzino.ServiceReference1.Articolo> GetProdottoAsync(int IDProdotto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaCategorie", ReplyAction="http://tempuri.org/IService1/ListaCategorieResponse")]
        int[] ListaCategorie();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaCategorie", ReplyAction="http://tempuri.org/IService1/ListaCategorieResponse")]
        System.Threading.Tasks.Task<int[]> ListaCategorieAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaProdotti", ReplyAction="http://tempuri.org/IService1/ListaProdottiResponse")]
        int[] ListaProdotti();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaProdotti", ReplyAction="http://tempuri.org/IService1/ListaProdottiResponse")]
        System.Threading.Tasks.Task<int[]> ListaProdottiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificaPassword", ReplyAction="http://tempuri.org/IService1/ModificaPasswordResponse")]
        bool ModificaPassword(string email, string psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificaPassword", ReplyAction="http://tempuri.org/IService1/ModificaPasswordResponse")]
        System.Threading.Tasks.Task<bool> ModificaPasswordAsync(string email, string psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificaProdotto", ReplyAction="http://tempuri.org/IService1/ModificaProdottoResponse")]
        bool ModificaProdotto(Magazzino.ServiceReference1.Articolo prodottoDaModificare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificaProdotto", ReplyAction="http://tempuri.org/IService1/ModificaProdottoResponse")]
        System.Threading.Tasks.Task<bool> ModificaProdottoAsync(Magazzino.ServiceReference1.Articolo prodottoDaModificare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuovaCategoria", ReplyAction="http://tempuri.org/IService1/NuovaCategoriaResponse")]
        bool NuovaCategoria(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuovaCategoria", ReplyAction="http://tempuri.org/IService1/NuovaCategoriaResponse")]
        System.Threading.Tasks.Task<bool> NuovaCategoriaAsync(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuovoProdotto", ReplyAction="http://tempuri.org/IService1/NuovoProdottoResponse")]
        bool NuovoProdotto(Magazzino.ServiceReference1.Articolo nuovo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuovoProdotto", ReplyAction="http://tempuri.org/IService1/NuovoProdottoResponse")]
        System.Threading.Tasks.Task<bool> NuovoProdottoAsync(Magazzino.ServiceReference1.Articolo nuovo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Registrazione", ReplyAction="http://tempuri.org/IService1/RegistrazioneResponse")]
        bool Registrazione(Magazzino.ServiceReference1.Utente nuovo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Registrazione", ReplyAction="http://tempuri.org/IService1/RegistrazioneResponse")]
        System.Threading.Tasks.Task<bool> RegistrazioneAsync(Magazzino.ServiceReference1.Utente nuovo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserLogin", ReplyAction="http://tempuri.org/IService1/UserLoginResponse")]
        int UserLogin(Magazzino.ServiceReference1.Login user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserLogin", ReplyAction="http://tempuri.org/IService1/UserLoginResponse")]
        System.Threading.Tasks.Task<int> UserLoginAsync(Magazzino.ServiceReference1.Login user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaMagazzinieri", ReplyAction="http://tempuri.org/IService1/ListaMagazzinieriResponse")]
        string[] ListaMagazzinieri();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaMagazzinieri", ReplyAction="http://tempuri.org/IService1/ListaMagazzinieriResponse")]
        System.Threading.Tasks.Task<string[]> ListaMagazzinieriAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMagazziniere", ReplyAction="http://tempuri.org/IService1/GetMagazziniereResponse")]
        Magazzino.ServiceReference1.Utente GetMagazziniere(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMagazziniere", ReplyAction="http://tempuri.org/IService1/GetMagazziniereResponse")]
        System.Threading.Tasks.Task<Magazzino.ServiceReference1.Utente> GetMagazziniereAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaProdottiDisponibili", ReplyAction="http://tempuri.org/IService1/ListaProdottiDisponibiliResponse")]
        int[] ListaProdottiDisponibili();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaProdottiDisponibili", ReplyAction="http://tempuri.org/IService1/ListaProdottiDisponibiliResponse")]
        System.Threading.Tasks.Task<int[]> ListaProdottiDisponibiliAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AumentaGiacenze", ReplyAction="http://tempuri.org/IService1/AumentaGiacenzeResponse")]
        bool AumentaGiacenze(int id, int quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AumentaGiacenze", ReplyAction="http://tempuri.org/IService1/AumentaGiacenzeResponse")]
        System.Threading.Tasks.Task<bool> AumentaGiacenzeAsync(int id, int quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DiminuisciGiacenze", ReplyAction="http://tempuri.org/IService1/DiminuisciGiacenzeResponse")]
        bool DiminuisciGiacenze(int id, int quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DiminuisciGiacenze", ReplyAction="http://tempuri.org/IService1/DiminuisciGiacenzeResponse")]
        System.Threading.Tasks.Task<bool> DiminuisciGiacenzeAsync(int id, int quantita);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Magazzino.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Magazzino.ServiceReference1.IService1>, Magazzino.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckEmail(string email) {
            return base.Channel.CheckEmail(email);
        }
        
        public System.Threading.Tasks.Task<bool> CheckEmailAsync(string email) {
            return base.Channel.CheckEmailAsync(email);
        }
        
        public bool EliminaProdotto(int id) {
            return base.Channel.EliminaProdotto(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminaProdottoAsync(int id) {
            return base.Channel.EliminaProdottoAsync(id);
        }
        
        public string GetCategoria(int id) {
            return base.Channel.GetCategoria(id);
        }
        
        public System.Threading.Tasks.Task<string> GetCategoriaAsync(int id) {
            return base.Channel.GetCategoriaAsync(id);
        }
        
        public Magazzino.ServiceReference1.Articolo GetProdotto(int IDProdotto) {
            return base.Channel.GetProdotto(IDProdotto);
        }
        
        public System.Threading.Tasks.Task<Magazzino.ServiceReference1.Articolo> GetProdottoAsync(int IDProdotto) {
            return base.Channel.GetProdottoAsync(IDProdotto);
        }
        
        public int[] ListaCategorie() {
            return base.Channel.ListaCategorie();
        }
        
        public System.Threading.Tasks.Task<int[]> ListaCategorieAsync() {
            return base.Channel.ListaCategorieAsync();
        }
        
        public int[] ListaProdotti() {
            return base.Channel.ListaProdotti();
        }
        
        public System.Threading.Tasks.Task<int[]> ListaProdottiAsync() {
            return base.Channel.ListaProdottiAsync();
        }
        
        public bool ModificaPassword(string email, string psw) {
            return base.Channel.ModificaPassword(email, psw);
        }
        
        public System.Threading.Tasks.Task<bool> ModificaPasswordAsync(string email, string psw) {
            return base.Channel.ModificaPasswordAsync(email, psw);
        }
        
        public bool ModificaProdotto(Magazzino.ServiceReference1.Articolo prodottoDaModificare) {
            return base.Channel.ModificaProdotto(prodottoDaModificare);
        }
        
        public System.Threading.Tasks.Task<bool> ModificaProdottoAsync(Magazzino.ServiceReference1.Articolo prodottoDaModificare) {
            return base.Channel.ModificaProdottoAsync(prodottoDaModificare);
        }
        
        public bool NuovaCategoria(string nome) {
            return base.Channel.NuovaCategoria(nome);
        }
        
        public System.Threading.Tasks.Task<bool> NuovaCategoriaAsync(string nome) {
            return base.Channel.NuovaCategoriaAsync(nome);
        }
        
        public bool NuovoProdotto(Magazzino.ServiceReference1.Articolo nuovo) {
            return base.Channel.NuovoProdotto(nuovo);
        }
        
        public System.Threading.Tasks.Task<bool> NuovoProdottoAsync(Magazzino.ServiceReference1.Articolo nuovo) {
            return base.Channel.NuovoProdottoAsync(nuovo);
        }
        
        public bool Registrazione(Magazzino.ServiceReference1.Utente nuovo) {
            return base.Channel.Registrazione(nuovo);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrazioneAsync(Magazzino.ServiceReference1.Utente nuovo) {
            return base.Channel.RegistrazioneAsync(nuovo);
        }
        
        public int UserLogin(Magazzino.ServiceReference1.Login user) {
            return base.Channel.UserLogin(user);
        }
        
        public System.Threading.Tasks.Task<int> UserLoginAsync(Magazzino.ServiceReference1.Login user) {
            return base.Channel.UserLoginAsync(user);
        }
        
        public string[] ListaMagazzinieri() {
            return base.Channel.ListaMagazzinieri();
        }
        
        public System.Threading.Tasks.Task<string[]> ListaMagazzinieriAsync() {
            return base.Channel.ListaMagazzinieriAsync();
        }
        
        public Magazzino.ServiceReference1.Utente GetMagazziniere(string id) {
            return base.Channel.GetMagazziniere(id);
        }
        
        public System.Threading.Tasks.Task<Magazzino.ServiceReference1.Utente> GetMagazziniereAsync(string id) {
            return base.Channel.GetMagazziniereAsync(id);
        }
        
        public int[] ListaProdottiDisponibili() {
            return base.Channel.ListaProdottiDisponibili();
        }
        
        public System.Threading.Tasks.Task<int[]> ListaProdottiDisponibiliAsync() {
            return base.Channel.ListaProdottiDisponibiliAsync();
        }
        
        public bool AumentaGiacenze(int id, int quantita) {
            return base.Channel.AumentaGiacenze(id, quantita);
        }
        
        public System.Threading.Tasks.Task<bool> AumentaGiacenzeAsync(int id, int quantita) {
            return base.Channel.AumentaGiacenzeAsync(id, quantita);
        }
        
        public bool DiminuisciGiacenze(int id, int quantita) {
            return base.Channel.DiminuisciGiacenze(id, quantita);
        }
        
        public System.Threading.Tasks.Task<bool> DiminuisciGiacenzeAsync(int id, int quantita) {
            return base.Channel.DiminuisciGiacenzeAsync(id, quantita);
        }
    }
}
