//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazzino.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckEmail", ReplyAction="http://tempuri.org/IService1/CheckEmailResponse")]
        bool CheckEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckEmail", ReplyAction="http://tempuri.org/IService1/CheckEmailResponse")]
        System.Threading.Tasks.Task<bool> CheckEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminaProdotto", ReplyAction="http://tempuri.org/IService1/EliminaProdottoResponse")]
        bool EliminaProdotto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminaProdotto", ReplyAction="http://tempuri.org/IService1/EliminaProdottoResponse")]
        System.Threading.Tasks.Task<bool> EliminaProdottoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategoria", ReplyAction="http://tempuri.org/IService1/GetCategoriaResponse")]
        string GetCategoria(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategoria", ReplyAction="http://tempuri.org/IService1/GetCategoriaResponse")]
        System.Threading.Tasks.Task<string> GetCategoriaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProdotto", ReplyAction="http://tempuri.org/IService1/GetProdottoResponse")]
        Server.Articolo GetProdotto(int IDProdotto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProdotto", ReplyAction="http://tempuri.org/IService1/GetProdottoResponse")]
        System.Threading.Tasks.Task<Server.Articolo> GetProdottoAsync(int IDProdotto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaCategorie", ReplyAction="http://tempuri.org/IService1/ListaCategorieResponse")]
        int[] ListaCategorie();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaCategorie", ReplyAction="http://tempuri.org/IService1/ListaCategorieResponse")]
        System.Threading.Tasks.Task<int[]> ListaCategorieAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaProdotti", ReplyAction="http://tempuri.org/IService1/ListaProdottiResponse")]
        int[] ListaProdotti();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaProdotti", ReplyAction="http://tempuri.org/IService1/ListaProdottiResponse")]
        System.Threading.Tasks.Task<int[]> ListaProdottiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificaPassword", ReplyAction="http://tempuri.org/IService1/ModificaPasswordResponse")]
        bool ModificaPassword(string email, string psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificaPassword", ReplyAction="http://tempuri.org/IService1/ModificaPasswordResponse")]
        System.Threading.Tasks.Task<bool> ModificaPasswordAsync(string email, string psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificaProdotto", ReplyAction="http://tempuri.org/IService1/ModificaProdottoResponse")]
        bool ModificaProdotto(Server.Articolo prodottoDaModificare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificaProdotto", ReplyAction="http://tempuri.org/IService1/ModificaProdottoResponse")]
        System.Threading.Tasks.Task<bool> ModificaProdottoAsync(Server.Articolo prodottoDaModificare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuovaCategoria", ReplyAction="http://tempuri.org/IService1/NuovaCategoriaResponse")]
        bool NuovaCategoria(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuovaCategoria", ReplyAction="http://tempuri.org/IService1/NuovaCategoriaResponse")]
        System.Threading.Tasks.Task<bool> NuovaCategoriaAsync(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuovoProdotto", ReplyAction="http://tempuri.org/IService1/NuovoProdottoResponse")]
        bool NuovoProdotto(Server.Articolo nuovo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NuovoProdotto", ReplyAction="http://tempuri.org/IService1/NuovoProdottoResponse")]
        System.Threading.Tasks.Task<bool> NuovoProdottoAsync(Server.Articolo nuovo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Registrazione", ReplyAction="http://tempuri.org/IService1/RegistrazioneResponse")]
        bool Registrazione(Server.Utente nuovo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Registrazione", ReplyAction="http://tempuri.org/IService1/RegistrazioneResponse")]
        System.Threading.Tasks.Task<bool> RegistrazioneAsync(Server.Utente nuovo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserLogin", ReplyAction="http://tempuri.org/IService1/UserLoginResponse")]
        int UserLogin(Server.Login user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserLogin", ReplyAction="http://tempuri.org/IService1/UserLoginResponse")]
        System.Threading.Tasks.Task<int> UserLoginAsync(Server.Login user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaMagazzinieri", ReplyAction="http://tempuri.org/IService1/ListaMagazzinieriResponse")]
        string[] ListaMagazzinieri();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaMagazzinieri", ReplyAction="http://tempuri.org/IService1/ListaMagazzinieriResponse")]
        System.Threading.Tasks.Task<string[]> ListaMagazzinieriAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMagazziniere", ReplyAction="http://tempuri.org/IService1/GetMagazziniereResponse")]
        Server.Utente GetMagazziniere(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMagazziniere", ReplyAction="http://tempuri.org/IService1/GetMagazziniereResponse")]
        System.Threading.Tasks.Task<Server.Utente> GetMagazziniereAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaProdottiDisponibili", ReplyAction="http://tempuri.org/IService1/ListaProdottiDisponibiliResponse")]
        int[] ListaProdottiDisponibili();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaProdottiDisponibili", ReplyAction="http://tempuri.org/IService1/ListaProdottiDisponibiliResponse")]
        System.Threading.Tasks.Task<int[]> ListaProdottiDisponibiliAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AumentaGiacenze", ReplyAction="http://tempuri.org/IService1/AumentaGiacenzeResponse")]
        bool AumentaGiacenze(int id, int quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AumentaGiacenze", ReplyAction="http://tempuri.org/IService1/AumentaGiacenzeResponse")]
        System.Threading.Tasks.Task<bool> AumentaGiacenzeAsync(int id, int quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DiminuisciGiacenze", ReplyAction="http://tempuri.org/IService1/DiminuisciGiacenzeResponse")]
        bool DiminuisciGiacenze(int id, int quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DiminuisciGiacenze", ReplyAction="http://tempuri.org/IService1/DiminuisciGiacenzeResponse")]
        System.Threading.Tasks.Task<bool> DiminuisciGiacenzeAsync(int id, int quantita);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Magazzino.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Magazzino.ServiceReference1.IService1>, Magazzino.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckEmail(string email) {
            return base.Channel.CheckEmail(email);
        }
        
        public System.Threading.Tasks.Task<bool> CheckEmailAsync(string email) {
            return base.Channel.CheckEmailAsync(email);
        }
        
        public bool EliminaProdotto(int id) {
            return base.Channel.EliminaProdotto(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminaProdottoAsync(int id) {
            return base.Channel.EliminaProdottoAsync(id);
        }
        
        public string GetCategoria(int id) {
            return base.Channel.GetCategoria(id);
        }
        
        public System.Threading.Tasks.Task<string> GetCategoriaAsync(int id) {
            return base.Channel.GetCategoriaAsync(id);
        }
        
        public Server.Articolo GetProdotto(int IDProdotto) {
            return base.Channel.GetProdotto(IDProdotto);
        }
        
        public System.Threading.Tasks.Task<Server.Articolo> GetProdottoAsync(int IDProdotto) {
            return base.Channel.GetProdottoAsync(IDProdotto);
        }
        
        public int[] ListaCategorie() {
            return base.Channel.ListaCategorie();
        }
        
        public System.Threading.Tasks.Task<int[]> ListaCategorieAsync() {
            return base.Channel.ListaCategorieAsync();
        }
        
        public int[] ListaProdotti() {
            return base.Channel.ListaProdotti();
        }
        
        public System.Threading.Tasks.Task<int[]> ListaProdottiAsync() {
            return base.Channel.ListaProdottiAsync();
        }
        
        public bool ModificaPassword(string email, string psw) {
            return base.Channel.ModificaPassword(email, psw);
        }
        
        public System.Threading.Tasks.Task<bool> ModificaPasswordAsync(string email, string psw) {
            return base.Channel.ModificaPasswordAsync(email, psw);
        }
        
        public bool ModificaProdotto(Server.Articolo prodottoDaModificare) {
            return base.Channel.ModificaProdotto(prodottoDaModificare);
        }
        
        public System.Threading.Tasks.Task<bool> ModificaProdottoAsync(Server.Articolo prodottoDaModificare) {
            return base.Channel.ModificaProdottoAsync(prodottoDaModificare);
        }
        
        public bool NuovaCategoria(string nome) {
            return base.Channel.NuovaCategoria(nome);
        }
        
        public System.Threading.Tasks.Task<bool> NuovaCategoriaAsync(string nome) {
            return base.Channel.NuovaCategoriaAsync(nome);
        }
        
        public bool NuovoProdotto(Server.Articolo nuovo) {
            return base.Channel.NuovoProdotto(nuovo);
        }
        
        public System.Threading.Tasks.Task<bool> NuovoProdottoAsync(Server.Articolo nuovo) {
            return base.Channel.NuovoProdottoAsync(nuovo);
        }
        
        public bool Registrazione(Server.Utente nuovo) {
            return base.Channel.Registrazione(nuovo);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrazioneAsync(Server.Utente nuovo) {
            return base.Channel.RegistrazioneAsync(nuovo);
        }
        
        public int UserLogin(Server.Login user) {
            return base.Channel.UserLogin(user);
        }
        
        public System.Threading.Tasks.Task<int> UserLoginAsync(Server.Login user) {
            return base.Channel.UserLoginAsync(user);
        }
        
        public string[] ListaMagazzinieri() {
            return base.Channel.ListaMagazzinieri();
        }
        
        public System.Threading.Tasks.Task<string[]> ListaMagazzinieriAsync() {
            return base.Channel.ListaMagazzinieriAsync();
        }
        
        public Server.Utente GetMagazziniere(string id) {
            return base.Channel.GetMagazziniere(id);
        }
        
        public System.Threading.Tasks.Task<Server.Utente> GetMagazziniereAsync(string id) {
            return base.Channel.GetMagazziniereAsync(id);
        }
        
        public int[] ListaProdottiDisponibili() {
            return base.Channel.ListaProdottiDisponibili();
        }
        
        public System.Threading.Tasks.Task<int[]> ListaProdottiDisponibiliAsync() {
            return base.Channel.ListaProdottiDisponibiliAsync();
        }
        
        public bool AumentaGiacenze(int id, int quantita) {
            return base.Channel.AumentaGiacenze(id, quantita);
        }
        
        public System.Threading.Tasks.Task<bool> AumentaGiacenzeAsync(int id, int quantita) {
            return base.Channel.AumentaGiacenzeAsync(id, quantita);
        }
        
        public bool DiminuisciGiacenze(int id, int quantita) {
            return base.Channel.DiminuisciGiacenze(id, quantita);
        }
        
        public System.Threading.Tasks.Task<bool> DiminuisciGiacenzeAsync(int id, int quantita) {
            return base.Channel.DiminuisciGiacenzeAsync(id, quantita);
        }
    }
}
